### ISSUE TITLE
JQuery 3.1.1 Compatability

### ISSUE THREAD

**Issue by gvijaybhaskar** [stanlemon/jGrowl#58]
JGrowl is not working with JQuery 3.1.1 version

**Comment by stanlemon** [comment]
@gvijaybhaskar Can you provide me with any other details?

**Comment by eric2971** [comment]
.size has been removed from 3.1.1.

Uncaught TypeError: $(...).size is not a function(…)$.jGrowl @ VM377 

	/** jGrowl Wrapper - Establish a base jGrowl Container for compatibility with older releases. **/
	$.jGrowl = function( m , o ) {
		// To maintain compatibility with older version that only supported one instance we'll create the base container.
		if ( $('#jGrowl').size() === 0 )
			$('<div id="jGrowl"></div>').addClass( (o && o.position) ? o.position : $.jGrowl.defaults.position ).appendTo('body');

**Comment by patrikx3** [comment]
You can fork and pull merge...

**Comment by gvijaybhaskar** [comment]
changed .size() to .length(), its good now. Thanks
